version: '3.7'
services:
  xray:
    container_name: xray
    image: xray:v1.0
    volumes:
      - ./xray:/etc/xray
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/fullchain.pem::/etc/nginx/fullchain.pem
      - ./nginx/certs/privkey.pem::/etc/nginx/privkey.pem
    ports:
      - "80:80"
      - "443:443"